# Case-by-case calls. Key: listing as printed (exact). Optional (year, listing) keys take precedence.
# Value: (type, description, bucket, confidence, basis)
# type: B business, I institutional, R residential household, H named apartment building / apartment heading,
#       V vacant, X unknown (heading with nothing under it)
from classify_rules import *

H_APT = ("H", "apartment building (named)", "", "high", "building name or APARTMENT heading")
UNID = lambda basis, conf="low": ("B", "unidentified business (name only)", B_UNK, conf, basis)

O = {
 # --- named apartment buildings / apartment headings
 "Rouseland Apts": H_APT, "Sutherland Apts": H_APT, "(Sutherland Apts)": H_APT, "SUTHERLAND APTS": H_APT,
 "Sunset Apts": H_APT, "Jensen's Apts": H_APT, "(Jensen Apts)": H_APT, "Spinning Apts": H_APT,
 "Kenmore Apts": H_APT, "Roberts Arms Apts": H_APT, "Bon-Air Apts": H_APT, "(Bon Air Apts) ofc": H_APT,
 "Echo Apts": H_APT, "MARIAN APTS": H_APT, "RENICK APARTMNT HSE": H_APT, "Renick Apartment House": H_APT,
 "[APARTMENT – no units listed]": ("H", "apartment building (heading, no units listed)", "", "high", "APARTMENT heading"),
 "Williamson The": ("H", "named building, likely apartments ('The Williamson')", "", "medium", "building-style name at a ½ address with a resident"),
 "[BUILDING – no units listed]": ("X", "building heading, no tenants listed", "", "low", "BUILDING heading only"),
 "[address printed, no name]": ("X", "address printed with no listing", "", "low", "number printed alone"),
 "Vacant": ("V", "vacant", "", "high", "printed 'Vacant'"),

 # --- businesses identified from the same name/phone at the same address in another year
 "NIKOLAS": ("B", "restaurant / cafe", B_REST, "high", "1960 'Nikola's restrnt', same phone"),
 "Nikola's": ("B", "restaurant / cafe", B_REST, "high", "1960 'Nikola's restrnt', same phone"),
 "NIKOLA'S": ("B", "restaurant / cafe", B_REST, "medium", "1960 'Nikola's restrnt' at same address"),
 "EMIDIOS ITALIAN-": ("B", "deli / specialty food", B_FOOD, "high", "truncated 'Emidio's Italian & American Food Mart'"),
 "WALLICK W ROY": ("B", "TV / radio sales & repair", B_HOME, "high", "1956-60 'Wallick W Roy Television & Radio', same phone"),
 "HALE L": ("B", "barber shop", B_PERS, "high", "1960 'Hale Luis brbr', same phone"),
 "Zuk S r": ("B", "shoe store", B_APP, "medium", "same phone as 'Zuk S shoe store' 1960-68"),
 "Zuk S": ("B", "shoe store", B_APP, "medium", "same phone as 'Zuk S shoe store' 1960-68"),
 "Sunset The": ("B", "bar / cocktail lounge", B_REST, "high", "1964-68 'SUNSET THE-COCKTAILS', same phone"),
 "COPPER LANTERN": ("B", "bar / cocktail lounge", B_REST, "high", "1960 'Copper Lantern tavern'"),
 "Silver Henry": ("B", "attorney's office", B_PROF, "high", "1956-68 'Silver Henry atty', same phone"),
 "Acebo Lorenzo": ("B", "record / music store", B_MEDIA, "medium", "1968 'ACEBO L-RECORDS' at same address"),
 "Hutchinson Chas B": ("B", "real estate / insurance", B_FIRE, "high", "listed with Hutchinson Realty Co, same phone"),
 "Schaefer Winston Inc": ("B", "real estate / property", B_FIRE, "medium", "later 'Winston Schaefer Realty Co'; same phone as Pioneer Mkt"),
 "Winston Schaefer Inc": ("B", "real estate / property", B_FIRE, "medium", "later 'Winston Schaefer Realty Co'; same phone as Pioneer Mkt"),
 "SCHAEFER WM INC": ("B", "real estate / property", B_FIRE, "medium", "same phone as 1956-60 'Winston Schaefer Inc'"),
 "LACHS H D": ("B", "optometrist's office", B_HEALTH, "high", "1956-60 'Lachs Harold D Dr optmtrst', same phone"),
 "Lachs Harold D Dr": ("B", "optometrist's office", B_HEALTH, "high", "same phone as earlier optometrist listing"),
 "BOHLENS LOGAN": ("B", "carpentry shop", B_IND, "high", "truncated 'Bohlen's Logan St Carpenter Shop'"),
 "Wesley Carl J": ("B", "physician's office", B_HEALTH, "medium", "1968 'WESLEY C J-MD', same phone"),
 "BERRYHILL GLENN": ("B", "dentist's office", B_HEALTH, "high", "1956-60 'Berryhill Glenn D dntst', same phone"),
 "ROWE S": ("B", "physician's office", B_HEALTH, "medium", "1956-60 'Rowe Stephen Dr', same phone"),
 "Raff's": ("B", "hardware / paint store", B_HOME, "high", "phones match Le Moyne Paint (1956) and Raff's Paint-Hdw (1964)"),
 "EMILIES": ("B", "gift / greeting card shop", B_RET, "high", "1956-60 'Emilie's greeting cards', 1965 gift shop"),
 "DIAZ RAFAEL J": ("B", "tax preparation", B_PROF, "medium", "same phone as 1973 'R & M Income Tax Service'; 1987 capitals"),
 "BAUMEN G G": ("B", "attorney's office", B_PROF, "high", "1956-60 'Baumen G G atty', same address"),
 "Baumen G G": ("B", "attorney's office", B_PROF, "high", "1956-60 'Baumen G G atty', same address"),
 "Simon E H": ("B", "insurance agency / accountant", B_FIRE, "high", "listed with Simon Ins Agcy and pub acct, same phone"),
 "SIMON E H": ("B", "insurance agency / accountant", B_FIRE, "high", "1956-60 Simon ins agcy / pub acct, same phone"),
 "EMPIRE CREDITORS": ("B", "collection agency", B_PROF, "high", "truncated 'Empire Creditors Serv'"),
 "Holmes Louis A": ("B", "insurance agency", B_FIRE, "medium", "same phone as 'Westrn Travelers Ins'"),
 "Caceres Victor M": ("B", "gas / service station", B_AUTO, "medium", "1987 'CACERES VICTOR CHEVRON SERVICE'; Standard Oil at same address 1973"),
 "Glynn Boxer & Phillips": ("B", "accountant", B_PROF, "medium", "1968 'GLYNN-BOXER-CPAS'"),
 "GLYNN BOXER & PHILLIPS": ("B", "accountant", B_PROF, "medium", "1968 'GLYNN-BOXER-CPAS'"),
 "El Prado": ("B", "bar / cocktail lounge", B_REST, "medium", "1968 'EL PRADO BEER BAR' at same address"),
 "EL PRADO": ("B", "bar / cocktail lounge", B_REST, "medium", "1968 'EL PRADO BEER BAR' at same address"),
 "RUDYS CORNER": ("B", "bar / cocktail lounge", B_REST, "medium", "same phone as 1973 'Little Joy Cocktails'"),
 "BERNAL A": ("B", "unidentified business (El Rodeo)", B_UNK, "medium", "same phone as 1973 'El Rodeo'"),
 "PETRIE GEORGE A": ("B", "finance / loan company", B_FIRE, "low", "same phone as 1973 'Bankers Financial Co'; 1987 capitals"),
 "Toni's": ("B", "shop (type not stated)", B_RET, "low", "same phone as 1956 'Jeanette's Children's Wear & Toys'"),
 "TONIS": ("B", "shop (type not stated)", B_RET, "low", "same name as 1960 'Toni's' next door"),
 "Leslie Jay": ("B", "shop (type not stated)", B_RET, "low", "listed as 'Jay Leslie's' at same address"),
 "Jay Leslie's": ("B", "shop (type not stated)", B_RET, "low", "possessive business name, no trade given"),
 "Leslie's Jay": ("B", "shop (type not stated)", B_RET, "low", "possessive business name, no trade given"),
 "Burgess E R Dick Col & Associates auctnrs": ("B", "auctioneer", B_PROF, "high", "'auctnrs'"),
 "Perrin C L carriages": ("B", "carriage maker / dealer", B_AUTO, "high", "'carriages'"),
 "Safeway Stores": ("B", "grocery / market", B_FOOD, "high", "Safeway grocery chain"),
 "White Cross Store No 38": ("B", "chain store, likely drugstore (White Cross)", B_HEALTH, "low", "numbered chain store; White Cross as a drug chain is general knowledge, not verified"),
 "Circle Rents & Sales": ("B", "rental & sales shop", B_RET, "low", "'rents & sales'"),
 "Aquafilter Westrn": ("B", "water filter company", B_UNK, "low", "name only"),
 "GISE E C": ("B", "investments office", B_FIRE, "high", "1956-60 'Gise E C investmts', same room & phone"),
 "DEUTSCH L": ("B", "dentist's office", B_HEALTH, "high", "1956-60 'Deutsch L dntst', same room & phone"),
 "CASS-JOHANSING": ("B", "insurance agency", B_FIRE, "high", "listed with CASS-JOHANSING-INS"),
 "Cass & Johansing": ("B", "insurance agency", B_FIRE, "medium", "1968 'CASS-JOHANSING-INS', same suite"),
 "CASS & JOHANSING": ("B", "insurance agency", B_FIRE, "medium", "1968 'CASS-JOHANSING-INS', same suite"),
 "LOS ANGELES COUNTY PROFESSIONAL PEACE": ("I", "professional / employee association", B_INST, "medium", "truncated '...PEACE OFFICERS'; same name as suite 430"),
 "PARK SUNSET BUILDING": ("B", "office building management", B_FIRE, "medium", "building office in suite"),
 "JWCH INSTITUTE INC": ("I", "nonprofit health institute", B_INST, "low", "'Institute'; JWCH as a nonprofit is general knowledge, not verified"),
 "HING ALBERT L AGENCY": ("B", "agency (likely insurance)", B_FIRE, "low", "'agency' in office suite"),
 "Mark-It Shopping List Inc": ("B", "shopping-list publisher / advertiser", B_MEDIA, "low", "name only, shares floor with TV Fanfare Publications"),
 "TRIDENT ENTERPRISES": ("B", "unidentified business (name only)", B_UNK, "low", "company name in an apartment unit"),
 "Central Sales & Serv Co": ("B", "sales & service co. (type not stated)", B_UNK, "low", "name only"),
 "Kelt Peter Central Sales & Serv Co": ("B", "sales & service co. (type not stated)", B_UNK, "low", "name only"),
 "CENTRAL SALES-SERV": ("B", "sales & service co. (type not stated)", B_UNK, "low", "name only"),
 "Sam's Serv": ("B", "service station (likely)", B_AUTO, "low", "'Serv' is the directory's usual word for service stations"),
 "McMahon's Serv": ("B", "service station (likely)", B_AUTO, "low", "'Serv' is the directory's usual word for service stations"),
 "Polychrome Corp": UNID("corporation, trade not stated"), "POLYCHROME CORP": UNID("corporation, trade not stated"),
 "Shade L B": ("B", "real estate / property", B_FIRE, "medium", "1956 'Shade L B rl est', same address"),
 "Gold Room The": ("B", "bar (likely)", B_REST, "low", "name only; long-running bar is general knowledge, not verified"),
 "GOLD ROOM THE": ("B", "bar (likely)", B_REST, "low", "name only; long-running bar is general knowledge, not verified"),
 "GOLD ROOM": ("B", "bar (likely)", B_REST, "low", "name only; long-running bar is general knowledge, not verified"),
 "Shack Inn": ("B", "bar / tavern (likely)", B_REST, "low", "'Inn' with no lodging context"),
 "Label Inn": ("B", "bar / tavern (likely)", B_REST, "low", "'Inn'; later a beer bar at the same address"),
 "LABEL INN THE": ("B", "bar / tavern (likely)", B_REST, "low", "'Inn'; later a beer bar at the same address"),
 "MIDNIGHT SUN": ("B", "bar or restaurant (likely)", B_REST, "low", "name only; restaurant before and tavern after at same address"),
 "George's Corner": ("B", "bar or cafe (likely)", B_REST, "low", "name only; 'Corner' successor is a bar"),
 "Larry's New Place": ("B", "bar or cafe (likely)", B_REST, "low", "name only"),
 "Acebo Lorenzo Larry's New Place": ("B", "bar or cafe (likely)", B_REST, "low", "name only"),
 "SWANK FRANK THE": ("B", "food stand (likely)", B_REST, "low", "name only ('frank' suggests hot dogs)"),
 "PESCADO MOJADO INC": ("B", "seafood restaurant or market (likely)", B_REST, "low", "name only ('wet fish')"),
 "LA ADELITA -SUNSET": UNID("name only; branch-style name"), "LA ADELITA-SUNSET": UNID("name only; branch-style name"),
 "Rose Mme": ("B", "unidentified (listing style suggests a proprietor, e.g. dressmaker)", B_UNK, "low", "'Mme' listed like a trade name"),
 "EL ESPANOL INTERNATL": UNID("name only"), "BEN'S SHOP": ("B", "shop (type not stated)", B_RET, "low", "name only"),
 "BODHI GARDENS": UNID("name only"), "Carmela's": UNID("possessive business name"), "CARMELA'S": UNID("possessive business name"),
 "Cinco": UNID("name only"), "SUCURSAL S": UNID("'sucursal' = branch office"), "ALMOS CORPORATION": UNID("corporation, trade not stated"),
 "UNIVERSAL PRODS-SALS": ("B", "products sales (likely wholesale)", B_IND, "low", "'prods-sals'"),
 "LOS PINOS": UNID("name only"), "Rodolfo's": UNID("possessive business name"), "WENSLEY COMPANY": UNID("company name"),
 "EL RODEO": UNID("name only"), "El Rodeo": UNID("name only"), "Fernandez & Lopez": UNID("partnership name"),
 "S C S Associates": ("B", "unidentified office (shares phone with Planned Equity Corp)", B_UNK, "low", "office building tenant"),
 "LEW & WANG": UNID("partnership name in office suite"), "YOUNG AND ASSOCIATES INC": UNID("company name in office suite"),
 "Young And Associates Inc": UNID("company name in office suite"), "M V C ASSOCIATES": UNID("company name in office suite"),
 "SHAMBALLA GLOBAL CORP": UNID("company name in office suite"),
 "DOLORES SHOP": ("B", "shop (type not stated)", B_RET, "low", "name only"),
 "Dolores' Shop": ("B", "shop (type not stated)", B_RET, "low", "name only"),
 "Dora's Shoppe": ("B", "shop (type not stated)", B_RET, "low", "name only"),
 "DORAS SHOPPE": ("B", "shop (type not stated)", B_RET, "low", "name only"),
 "NENA'S SHOPPE": ("B", "shop (type not stated)", B_RET, "low", "name only"),
 "Kay Harry J mdsng": ("B", "merchandise / general goods", B_RET, "low", "'mdsng'"),
 "Woodstock Gallery": ("B", "art gallery / shop", B_RET, "medium", "'Gallery'"),
 "FINER DAVID STUDIOS": ("B", "studio (type not stated)", B_MEDIA, "low", "'Studios', shares address with Finer's clothing store"),
}

# year-specific
OY = {
 (1987, "HANSEN AL B"): ("B", "unidentified business (personal name in capitals)", B_UNK, "low", "1987 capitals; earlier years look residential (owner of apartments at this address?)"),
}

# lots treated as office buildings: an unmatched personal/company name in a suite is an office tenant, not a household
OFFICE_LOTS = {1910, 1900}
